export const data = [
    {
      "id": 1,
      "title": "React.js Crash Course",
      "description": "Learn the basics of React.js in this comprehensive crash course.",
      "url": "https://www.youtube.com/embed/s2skans2dP4?si=KmvNLyWZHs9EWFcB",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Education",
      "duration": "2:30:00",
      "uploadDate": "2024-01-15",
      "views": 1024500,
      "likes": 12000,
      "dislikes": 500
    },
    {
      "id": 2,
      "title": "Node.js REST API Tutorial",
      "description": "Build REST APIs with Node.js and Express in this tutorial.",
      "url": "https://www.youtube.com/embed/uNCrMvkPUAE?si=Nqo0zKgzFKFNZ9lx",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "1:45:00",
      "uploadDate": "2024-02-10",
      "views": 875000,
      "likes": 9500,
      "dislikes": 300
    },
    {
      "id": 3,
      "title": "Yoga for Beginners",
      "description": "A 30-minute beginner's yoga routine to start your day fresh.",
      "url": "https://www.youtube.com/embed/brjAjq4zEIE?si=qqSIEMJgCDUVaM_j",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Health & Fitness",
      "duration": "0:30:00",
      "uploadDate": "2024-03-05",
      "views": 680000,
      "likes": 7500,
      "dislikes": 150
    },
    {
      "id": 4,
      "title": "CSS Grid Tutorial",
      "description": "Master CSS Grid and build complex layouts with ease.",
      "url": "https://www.youtube.com/embed/EiNiSFIPIQE?si=9YY0XAPPmdrxwKrr",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Web Development",
      "duration": "1:00:00",
      "uploadDate": "2024-02-20",
      "views": 530000,
      "likes": 6300,
      "dislikes": 200
    },
    {
      "id": 5,
      "title": "Exploring Italy - Travel Vlog",
      "description": "Join us on an amazing journey through Italy’s most beautiful cities.",
      "url": "https://www.youtube.com/embed/BbegGNcvMb0?si=p0RZmxztn4QygWf9",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Travel",
      "duration": "1:20:00",
      "uploadDate": "2024-05-01",
      "views": 870000,
      "likes": 8000,
      "dislikes": 220
    },
    {
      "id": 6,
      "title": "Python for Data Science",
      "description": "Get started with Python programming for data science.",
      "url": "https://www.youtube.com/embed/7DSpYPja9qM?si=860y9yD3lkScpU5o",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Education",
      "duration": "3:00:00",
      "uploadDate": "2024-06-15",
      "views": 940000,
      "likes": 11000,
      "dislikes": 320
    },
    {
      "id": 7,
      "title": "How to Make Sushi at Home",
      "description": "Learn how to make delicious sushi with simple ingredients.",
      "url": "https://www.youtube.com/embed/aDQxH-KpCCc?si=8ABX11G-kPxioXFE",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Cooking",
      "duration": "0:40:00",
      "uploadDate": "2024-07-05",
      "views": 310000,
      "likes": 4200,
      "dislikes": 80
    },
    {
      "id": 8,
      "title": "Mastering JavaScript ES6+",
      "description": "Advanced concepts of JavaScript ES6 and beyond.",
      "url": "https://www.youtube.com/embed/VCD32WkdWvs?si=5yXKtAj7IUCQAEI3",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "1:50:00",
      "uploadDate": "2024-08-10",
      "views": 600000,
      "likes": 7500,
      "dislikes": 250
    },
    {
      "id": 9,
      "title": "10-Minute Morning Meditation",
      "description": "Start your day with this peaceful 10-minute meditation.",
      "url": "https://www.youtube.com/embed/ENYYb5vIMkU?si=ZEJH4i1V_6QxROPV",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Health & Fitness",
      "duration": "0:10:00",
      "uploadDate": "2024-09-01",
      "views": 225000,
      "likes": 3200,
      "dislikes": 50
    },
    {
      "id": 10,
      "title": "DIY Home Renovation Tips",
      "description": "Essential tips for renovating your home on a budget.",
      "url": "https://www.youtube.com/embed/taO2_XYX4M4?si=-KiQ_zb6lGEDdWvD",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "DIY",
      "duration": "0:50:00",
      "uploadDate": "2024-09-15",
      "views": 460000,
      "likes": 5200,
      "dislikes": 130
    },
    {
      "id": 11,
      "title": "The History of Artificial Intelligence AI",
      "description": "A deep dive into the history and future of AI.",
      "url": "https://www.youtube.com/embed/fBncbUmO-L4?si=pl7q_1XDPDaBEWpE",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "2:00:00",
      "uploadDate": "2024-10-01",
      "views": 770000,
      "likes": 8900,
      "dislikes": 400
    },
    {
      "id": 12,
      "title": "Quick & Easy Vegan Recipes",
      "description": "Five quick and easy vegan recipes you can make in under 30 minutes.",
      "url": "https://www.youtube.com/embed/JHI-6MSA0l4?si=UKHYuwz2P5y-LDf3",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Cooking",
      "duration": "0:35:00",
      "uploadDate": "2024-07-20",
      "views": 410000,
      "likes": 4800,
      "dislikes": 100
    },
    {
      "id": 13,
      "title": "How to Build a Mobile App with React Native",
      "description": "Step-by-step guide to building a mobile app using React Native.",
      "url": "https://www.youtube.com/embed/gvkqT_Uoahw?si=Eew7VOf5XXzEoO2t",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "2:15:00",
      "uploadDate": "2024-08-25",
      "views": 520000,
      "likes": 6800,
      "dislikes": 210
    },
    {
      "id": 14,
      "title": "Photography Basics - Getting Started with DSLR",
      "description": "Learn the fundamentals of photography with this DSLR beginner's guide.",
      "url": "https://www.youtube.com/embed/hVuTuib65WM?si=6AO3m4OtPj5rcucg",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Education",
      "duration": "1:20:00",
      "uploadDate": "2024-06-05",
      "views": 640000,
      "likes": 7200,
      "dislikes": 160
    },
    {
      "id": 15,
      "title": "Full-Body Workout - No Equipment",
      "description": "This 45-minute full-body workout requires no equipment and can be done anywhere.",
      "url": "https://www.youtube.com/embed/FLQqCyhTQdE?si=lJZ-zC7dPE-YqyQM",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Health & Fitness",
      "duration": "0:45:00",
      "uploadDate": "2024-04-10",
      "views": 570000,
      "likes": 6300,
      "dislikes": 120
    },
    {
      "id": 16,
      "title": "Coding Interview Questions - JavaScript",
      "description": "Tackle some common JavaScript interview questions in this tutorial.",
      "url": "https://www.youtube.com/embed/zmk32_QA71s?si=lhjFkTLw7gmh54XJ",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "1:30:00",
      "uploadDate": "2024-05-15",
      "views": 430000,
      "likes": 5000,
      "dislikes": 180
    },
    {
      "id": 17,
      "title": "How to Play Guitar - Beginner Lessons",
      "description": "Start learning how to play the guitar with these beginner-friendly lessons.",
      "url": "https://www.youtube.com/embed/BBz-Jyr23M4?si=ZplIGLZAy_3n_FgN",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Music",
      "duration": "1:30:00",
      "uploadDate": "2024-09-20",
      "views": 360000,
      "likes": 4100,
      "dislikes": 90
    },
    {
      "id": 18,
      "title": "Understanding Blockchain Technology",
      "description": "An in-depth look at blockchain technology and its applications.",
      "url": "https://www.youtube.com/embed/YJyXfjbBmc8?si=MAxv8CdfSoE8mWXf",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "2:10:00",
      "uploadDate": "2024-05-05",
      "views": 850000,
      "likes": 9400,
      "dislikes": 340
    },
    {
      "id": 19,
      "title": "Street Photography Tips & Tricks",
      "description": "Capture the perfect street photo with these tips and tricks.",
      "url": "https://www.youtube.com/embed/hVuTuib65WM?si=6AO3m4OtPj5rcucg",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Art",
      "duration": "0:55:00",
      "uploadDate": "2024-03-15",
      "views": 220000,
      "likes": 2900,
      "dislikes": 70
    },
    {
      "id": 20,
      "title": "Learning Swift Programming",
      "description": "Beginner's guide to learning Swift programming for iOS development.",
      "url": "https://www.youtube.com/embed/CuB3dg8F3sY?si=4dS4elBM4Htioq_J",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Technology",
      "duration": "2:00:00",
      "uploadDate": "2024-09-10",
      "views": 670000,
      "likes": 7600,
      "dislikes": 210
    }
  ]
  